branch-defaults:
  deployBeanstalk:
    environment: jdo-front-react-env
    group_suffix: null
deploy:
  artifact: C:\Users\Ju\Projetos\jdo-front-react\jdo-front-react-v1.zip
global:
  application_name: jdo-front-react
  branch: null
  default_ec2_keyname: default
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
